### ISSUE TITLE
could not detect go version

### ISSUE THREAD

**Issue by frzifus** [keyval-dev/opentelemetry-go-instrumentation#12]
# Expected Behavior
A stable connection to the collector.

# Actual Behavior
Program terminates because the go version is not identified.

# Steps to Reproduce the Problem

1. `podman run --network=host --rm -it jaegertracing/opentelemetry-all-in-one:latest`
2. `make build && OTEL_SERVICE_NAME=test OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317 OTEL_TARGET_EXE=${PWD}/unstripped ./kv-go-instrumentation`
3. `./unstripped` (gorilla mux http server)

# Additional Info

- operation-system/kernel version:
  
  **Output of `awk -F '=' '/PRETTY_NAME/ { print $2 }' /etc/os-release`:**
  **Output of `uname -r`:**
  ```
  "Fedora Linux 35 (Workstation Edition)"
  5.17.4-200.fc35.x86_64
  ```

- binary strings `strings unstripped | grep "Go buildinf" -A 1`:
 ```                                                                      
Go buildinf:
go1.18
 ```

- go version:
```
go version go1.18 linux/amd64
```

- log:
```
{"level":"info","ts":1651701304.5921707,"caller":"cli/main.go:22","msg":"starting Go OpenTelemetry Agent ..."}
{"level":"info","ts":1651701304.5922222,"caller":"opentelemetry/controller.go:97","msg":"Establishing connection to OpenTelemetry collector ..."}
{"level":"info","ts":1651701306.6052349,"caller":"process/discover.go:37","msg":"process not found yet, trying again soon","exe_path":"/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/unstripped"}
{"level":"info","ts":1651701308.5969474,"caller":"process/discover.go:37","msg":"process not found yet, trying again soon","exe_path":"/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/unstripped"}
{"level":"info","ts":1651701310.5970006,"caller":"process/discover.go:42","msg":"found process","pid":1131585}
{"level":"error","ts":1651701310.5971448,"caller":"cli/main.go:61","msg":"error while analyzing target process","error":"could not detect go version","stacktrace":"main.main\n\t/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/cli/main.go:61\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250"}
```

**Comment by withlin** [comment]
@frzifus may be not support  golang 1.18 version. see  the source code :https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/master/pkg/inject/offset_results.json#L12

**Comment by frzifus** [comment]
Will try it this evening with a go 1.17 version. It seems that the program is failing here [[module.go#L69](https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/master/pkg/process/module.go#L69)]. 

Looking at the trace, is `offset_results.json` even considered at this point?
```golang
goroutine 1 [running]:
github.com/keyval-dev/opentelemetry-go-instrumentation/pkg/process.getGoDetails(0xc0000f40a0)
	/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/pkg/process/module.go:77 +0x58c
github.com/keyval-dev/opentelemetry-go-instrumentation/pkg/process.(*processAnalyzer).getModuleDetails(0xb184c0?, 0xc0000d8190?)
	/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/pkg/process/module.go:20 +0x2e
github.com/keyval-dev/opentelemetry-go-instrumentation/pkg/process.(*processAnalyzer).Analyze(0xc00007c1b0?, 0x11d4f7, 0x2?)
	/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/pkg/process/analyze.go:67 +0x14e
main.main()
	/home/frzifus/git/go/observability/opentelemetry-go-instrumentation/cli/main.go:59 +0x37f
```

**Comment by edeNFed** [comment]
@frzifus @withlin  it does look like an issue with instrumenting Go 1.18, as a quick workaround I think trying Go 1.17 should work.

I can think of several fixes that need to be made:
1. Go detection version: It looks like the logic changed a little bit in Go 1.18.
    * The original code: https://cs.opensource.google/go/go/+/refs/tags/go1.17.6:src/cmd/go/internal/version/version.go;l=169
    * Go 1.18 updated version: https://cs.opensource.google/go/go/+/refs/tags/go1.18.1:src/debug/buildinfo/buildinfo.go;drc=a131fd1313e0056ad094d234c67648409d081b8c;l=99

2.  Regenerate the `offset_results.json` file to include newer versions. In the future, this should happen automatically via GitHub Action.

3. Implement fallback logic in case of missing offset:
   * if the current version is higher than the max version in the file: use the max version
   * If the current version is lower than the min version in the file: use the min version

I will have a PR for fixing the first issue soon.

**Comment by edeNFed** [comment]
Hi @frzifus please try again with version v0.5.3. It includes the go 1.18 fix.
