### ISSUE TITLE
can this work with serverless platforms like Cloud Run?

### ISSUE THREAD

**Issue by willie** [keyval-dev/opentelemetry-go-instrumentation#27]
### Feature request

I'm largely deploying Go apps to Cloud Run and automatic instrumentation would be awesome. The docs only refer to k8s setups.

### Use case

k8s is pretty complicated and for my apps, Cloud Run is a good match. I imagine other folks are deploying Go apps using other serverless platforms, too, and it would be helpful to be able to use this here vs. manual instrumentation.

**Comment by edeNFed** [comment]
Hi, 
Unfortunately, it looks like currently [Cloud Run does not support eBPF](https://issuetracker.google.com/issues/206477810) which is a requirement for running this instrumentation.

**Comment by willie** [comment]
Thank you @edeNFed. I don't know how I missed it, but I appreciate you taking the time to find it out. I'll pass along a request through our GCP channels to try and get eBPF support.
