### ISSUE TITLE
Doubt about trace ID

### ISSUE THREAD

**Issue by EvanLjp** [keyval-dev/opentelemetry-go-instrumentation#29]
After read the whole codes, I don't find any codes to send the trace ID in the different services. May be I don't find it. Could you share the parts for me? Thanks a lot ~

**Comment by edeNFed** [comment]
Hi, if you are referring to context propagation (sending trace id over request headers), we just released that.
Please check out v0.6.0

**Comment by yfractal** [comment]
I guess relates code is here

https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/483a2658fbf4d58ae0ef997709c0fac44966bf99/pkg/instrumentors/bpf/google/golang/org/grpc/bpf/probe.bpf.c#L150-L157

`append_item_to_slice` will do writing

**Comment by EvanLjp** [comment]
Thx a lot, there was no code for that at the time I asked. I would read the related PRs.

> I guess relates code is here
> 
> https://github.com/keyval-dev/opentelemetry-go-instrumentation/blob/483a2658fbf4d58ae0ef997709c0fac44966bf99/pkg/instrumentors/bpf/google/golang/org/grpc/bpf/probe.bpf.c#L150-L157
> 
> `append_item_to_slice` will do writing
